var hierarchy =
[
    [ "AGlib", "class_a_glib.html", [
      [ "LOVE", "class_l_o_v_e.html", null ],
      [ "SFML", "class_s_f_m_l.html", null ]
    ] ],
    [ "sf::BlendMode", "structsf_1_1_blend_mode.html", null ],
    [ "sf::SoundStream::Chunk", "structsf_1_1_sound_stream_1_1_chunk.html", null ],
    [ "sf::Clock", "classsf_1_1_clock.html", null ],
    [ "sf::Color", "classsf_1_1_color.html", null ],
    [ "sf::ContextSettings", "structsf_1_1_context_settings.html", null ],
    [ "sf::Shader::CurrentTextureType", "structsf_1_1_shader_1_1_current_texture_type.html", null ],
    [ "sf::Drawable", "classsf_1_1_drawable.html", [
      [ "sf::Shape", "classsf_1_1_shape.html", [
        [ "sf::CircleShape", "classsf_1_1_circle_shape.html", null ],
        [ "sf::CircleShape", "classsf_1_1_circle_shape.html", null ],
        [ "sf::CircleShape", "classsf_1_1_circle_shape.html", null ],
        [ "sf::CircleShape", "classsf_1_1_circle_shape.html", null ],
        [ "sf::ConvexShape", "classsf_1_1_convex_shape.html", null ],
        [ "sf::ConvexShape", "classsf_1_1_convex_shape.html", null ],
        [ "sf::ConvexShape", "classsf_1_1_convex_shape.html", null ],
        [ "sf::ConvexShape", "classsf_1_1_convex_shape.html", null ],
        [ "sf::RectangleShape", "classsf_1_1_rectangle_shape.html", null ],
        [ "sf::RectangleShape", "classsf_1_1_rectangle_shape.html", null ],
        [ "sf::RectangleShape", "classsf_1_1_rectangle_shape.html", null ],
        [ "sf::RectangleShape", "classsf_1_1_rectangle_shape.html", null ]
      ] ],
      [ "sf::Shape", "classsf_1_1_shape.html", null ],
      [ "sf::Shape", "classsf_1_1_shape.html", null ],
      [ "sf::Shape", "classsf_1_1_shape.html", null ],
      [ "sf::Sprite", "classsf_1_1_sprite.html", null ],
      [ "sf::Sprite", "classsf_1_1_sprite.html", null ],
      [ "sf::Sprite", "classsf_1_1_sprite.html", null ],
      [ "sf::Sprite", "classsf_1_1_sprite.html", null ],
      [ "sf::Text", "classsf_1_1_text.html", null ],
      [ "sf::Text", "classsf_1_1_text.html", null ],
      [ "sf::Text", "classsf_1_1_text.html", null ],
      [ "sf::Text", "classsf_1_1_text.html", null ],
      [ "sf::VertexArray", "classsf_1_1_vertex_array.html", null ],
      [ "sf::VertexArray", "classsf_1_1_vertex_array.html", null ],
      [ "sf::VertexArray", "classsf_1_1_vertex_array.html", null ],
      [ "sf::VertexArray", "classsf_1_1_vertex_array.html", null ]
    ] ],
    [ "sf::Event", "classsf_1_1_event.html", null ],
    [ "Glib::Event", "class_glib_1_1_event.html", null ],
    [ "exception", null, [
      [ "Glib::Exception", "class_glib_1_1_exception.html", null ]
    ] ],
    [ "sf::Font", "classsf_1_1_font.html", null ],
    [ "Glib", "class_glib.html", null ],
    [ "sf::GlResource", "classsf_1_1_gl_resource.html", [
      [ "sf::Context", "classsf_1_1_context.html", null ],
      [ "sf::Context", "classsf_1_1_context.html", null ],
      [ "sf::Context", "classsf_1_1_context.html", null ],
      [ "sf::Context", "classsf_1_1_context.html", null ],
      [ "sf::Shader", "classsf_1_1_shader.html", null ],
      [ "sf::Shader", "classsf_1_1_shader.html", null ],
      [ "sf::Shader", "classsf_1_1_shader.html", null ],
      [ "sf::Shader", "classsf_1_1_shader.html", null ],
      [ "sf::Texture", "classsf_1_1_texture.html", null ],
      [ "sf::Texture", "classsf_1_1_texture.html", null ],
      [ "sf::Texture", "classsf_1_1_texture.html", null ],
      [ "sf::Texture", "classsf_1_1_texture.html", null ],
      [ "sf::Window", "classsf_1_1_window.html", [
        [ "sf::RenderWindow", "classsf_1_1_render_window.html", null ],
        [ "sf::RenderWindow", "classsf_1_1_render_window.html", null ],
        [ "sf::RenderWindow", "classsf_1_1_render_window.html", null ],
        [ "sf::RenderWindow", "classsf_1_1_render_window.html", null ]
      ] ],
      [ "sf::Window", "classsf_1_1_window.html", null ],
      [ "sf::Window", "classsf_1_1_window.html", null ],
      [ "sf::Window", "classsf_1_1_window.html", null ]
    ] ],
    [ "sf::Glyph", "classsf_1_1_glyph.html", null ],
    [ "sf::Joystick::Identification", "structsf_1_1_joystick_1_1_identification.html", null ],
    [ "sf::Image", "classsf_1_1_image.html", null ],
    [ "sf::Font::Info", "structsf_1_1_font_1_1_info.html", null ],
    [ "sf::InputStream", "classsf_1_1_input_stream.html", null ],
    [ "sf::IpAddress", "classsf_1_1_ip_address.html", null ],
    [ "sf::Joystick", "classsf_1_1_joystick.html", null ],
    [ "sf::Event::JoystickButtonEvent", "structsf_1_1_event_1_1_joystick_button_event.html", null ],
    [ "sf::Event::JoystickConnectEvent", "structsf_1_1_event_1_1_joystick_connect_event.html", null ],
    [ "sf::Event::JoystickMoveEvent", "structsf_1_1_event_1_1_joystick_move_event.html", null ],
    [ "sf::Keyboard", "classsf_1_1_keyboard.html", null ],
    [ "sf::Event::KeyEvent", "structsf_1_1_event_1_1_key_event.html", null ],
    [ "sf::Listener", "classsf_1_1_listener.html", null ],
    [ "sf::Mouse", "classsf_1_1_mouse.html", null ],
    [ "sf::Event::MouseButtonEvent", "structsf_1_1_event_1_1_mouse_button_event.html", null ],
    [ "sf::Event::MouseMoveEvent", "structsf_1_1_event_1_1_mouse_move_event.html", null ],
    [ "sf::Event::MouseWheelEvent", "structsf_1_1_event_1_1_mouse_wheel_event.html", null ],
    [ "sf::NonCopyable", "classsf_1_1_non_copyable.html", [
      [ "sf::Context", "classsf_1_1_context.html", null ],
      [ "sf::Context", "classsf_1_1_context.html", null ],
      [ "sf::Context", "classsf_1_1_context.html", null ],
      [ "sf::Context", "classsf_1_1_context.html", null ],
      [ "sf::Ftp", "classsf_1_1_ftp.html", null ],
      [ "sf::Ftp", "classsf_1_1_ftp.html", null ],
      [ "sf::Ftp", "classsf_1_1_ftp.html", null ],
      [ "sf::Ftp", "classsf_1_1_ftp.html", null ],
      [ "sf::Http", "classsf_1_1_http.html", null ],
      [ "sf::Http", "classsf_1_1_http.html", null ],
      [ "sf::Http", "classsf_1_1_http.html", null ],
      [ "sf::Http", "classsf_1_1_http.html", null ],
      [ "sf::Lock", "classsf_1_1_lock.html", null ],
      [ "sf::Lock", "classsf_1_1_lock.html", null ],
      [ "sf::Lock", "classsf_1_1_lock.html", null ],
      [ "sf::Lock", "classsf_1_1_lock.html", null ],
      [ "sf::Mutex", "classsf_1_1_mutex.html", null ],
      [ "sf::Mutex", "classsf_1_1_mutex.html", null ],
      [ "sf::Mutex", "classsf_1_1_mutex.html", null ],
      [ "sf::Mutex", "classsf_1_1_mutex.html", null ],
      [ "sf::RenderTarget", "classsf_1_1_render_target.html", [
        [ "sf::RenderTexture", "classsf_1_1_render_texture.html", null ],
        [ "sf::RenderTexture", "classsf_1_1_render_texture.html", null ],
        [ "sf::RenderTexture", "classsf_1_1_render_texture.html", null ],
        [ "sf::RenderTexture", "classsf_1_1_render_texture.html", null ],
        [ "sf::RenderWindow", "classsf_1_1_render_window.html", null ],
        [ "sf::RenderWindow", "classsf_1_1_render_window.html", null ],
        [ "sf::RenderWindow", "classsf_1_1_render_window.html", null ],
        [ "sf::RenderWindow", "classsf_1_1_render_window.html", null ]
      ] ],
      [ "sf::RenderTarget", "classsf_1_1_render_target.html", null ],
      [ "sf::RenderTarget", "classsf_1_1_render_target.html", null ],
      [ "sf::RenderTarget", "classsf_1_1_render_target.html", null ],
      [ "sf::Shader", "classsf_1_1_shader.html", null ],
      [ "sf::Shader", "classsf_1_1_shader.html", null ],
      [ "sf::Shader", "classsf_1_1_shader.html", null ],
      [ "sf::Shader", "classsf_1_1_shader.html", null ],
      [ "sf::Socket", "classsf_1_1_socket.html", [
        [ "sf::TcpListener", "classsf_1_1_tcp_listener.html", null ],
        [ "sf::TcpListener", "classsf_1_1_tcp_listener.html", null ],
        [ "sf::TcpListener", "classsf_1_1_tcp_listener.html", null ],
        [ "sf::TcpListener", "classsf_1_1_tcp_listener.html", null ],
        [ "sf::TcpSocket", "classsf_1_1_tcp_socket.html", null ],
        [ "sf::TcpSocket", "classsf_1_1_tcp_socket.html", null ],
        [ "sf::TcpSocket", "classsf_1_1_tcp_socket.html", null ],
        [ "sf::TcpSocket", "classsf_1_1_tcp_socket.html", null ],
        [ "sf::UdpSocket", "classsf_1_1_udp_socket.html", null ],
        [ "sf::UdpSocket", "classsf_1_1_udp_socket.html", null ],
        [ "sf::UdpSocket", "classsf_1_1_udp_socket.html", null ],
        [ "sf::UdpSocket", "classsf_1_1_udp_socket.html", null ]
      ] ],
      [ "sf::Socket", "classsf_1_1_socket.html", null ],
      [ "sf::Socket", "classsf_1_1_socket.html", null ],
      [ "sf::Socket", "classsf_1_1_socket.html", null ],
      [ "sf::Thread", "classsf_1_1_thread.html", null ],
      [ "sf::Thread", "classsf_1_1_thread.html", null ],
      [ "sf::Thread", "classsf_1_1_thread.html", null ],
      [ "sf::Thread", "classsf_1_1_thread.html", null ],
      [ "sf::ThreadLocal", "classsf_1_1_thread_local.html", [
        [ "sf::ThreadLocalPtr< T >", "classsf_1_1_thread_local_ptr.html", null ],
        [ "sf::ThreadLocalPtr< T >", "classsf_1_1_thread_local_ptr.html", null ],
        [ "sf::ThreadLocalPtr< T >", "classsf_1_1_thread_local_ptr.html", null ],
        [ "sf::ThreadLocalPtr< T >", "classsf_1_1_thread_local_ptr.html", null ]
      ] ],
      [ "sf::ThreadLocal", "classsf_1_1_thread_local.html", null ],
      [ "sf::ThreadLocal", "classsf_1_1_thread_local.html", null ],
      [ "sf::ThreadLocal", "classsf_1_1_thread_local.html", null ],
      [ "sf::Window", "classsf_1_1_window.html", null ],
      [ "sf::Window", "classsf_1_1_window.html", null ],
      [ "sf::Window", "classsf_1_1_window.html", null ],
      [ "sf::Window", "classsf_1_1_window.html", null ]
    ] ],
    [ "sf::Packet", "classsf_1_1_packet.html", null ],
    [ "sf::Rect< T >", "classsf_1_1_rect.html", null ],
    [ "sf::Rect< float >", "classsf_1_1_rect.html", null ],
    [ "sf::Rect< int >", "classsf_1_1_rect.html", null ],
    [ "sf::RenderStates", "classsf_1_1_render_states.html", null ],
    [ "sf::Http::Request", "classsf_1_1_http_1_1_request.html", null ],
    [ "sf::Ftp::Response", "classsf_1_1_ftp_1_1_response.html", [
      [ "sf::Ftp::DirectoryResponse", "classsf_1_1_ftp_1_1_directory_response.html", null ],
      [ "sf::Ftp::DirectoryResponse", "classsf_1_1_ftp_1_1_directory_response.html", null ],
      [ "sf::Ftp::DirectoryResponse", "classsf_1_1_ftp_1_1_directory_response.html", null ],
      [ "sf::Ftp::DirectoryResponse", "classsf_1_1_ftp_1_1_directory_response.html", null ],
      [ "sf::Ftp::ListingResponse", "classsf_1_1_ftp_1_1_listing_response.html", null ],
      [ "sf::Ftp::ListingResponse", "classsf_1_1_ftp_1_1_listing_response.html", null ],
      [ "sf::Ftp::ListingResponse", "classsf_1_1_ftp_1_1_listing_response.html", null ],
      [ "sf::Ftp::ListingResponse", "classsf_1_1_ftp_1_1_listing_response.html", null ]
    ] ],
    [ "sf::Http::Response", "classsf_1_1_http_1_1_response.html", null ],
    [ "sf::Sensor", "classsf_1_1_sensor.html", null ],
    [ "sf::Event::SensorEvent", "structsf_1_1_event_1_1_sensor_event.html", null ],
    [ "sf::Event::SizeEvent", "structsf_1_1_event_1_1_size_event.html", null ],
    [ "sf::SocketSelector", "classsf_1_1_socket_selector.html", null ],
    [ "sf::SoundBuffer", "classsf_1_1_sound_buffer.html", null ],
    [ "sf::SoundRecorder", "classsf_1_1_sound_recorder.html", [
      [ "sf::SoundBufferRecorder", "classsf_1_1_sound_buffer_recorder.html", null ],
      [ "sf::SoundBufferRecorder", "classsf_1_1_sound_buffer_recorder.html", null ],
      [ "sf::SoundBufferRecorder", "classsf_1_1_sound_buffer_recorder.html", null ],
      [ "sf::SoundBufferRecorder", "classsf_1_1_sound_buffer_recorder.html", null ]
    ] ],
    [ "sf::SoundSource", "classsf_1_1_sound_source.html", [
      [ "sf::Sound", "classsf_1_1_sound.html", null ],
      [ "sf::Sound", "classsf_1_1_sound.html", null ],
      [ "sf::Sound", "classsf_1_1_sound.html", null ],
      [ "sf::Sound", "classsf_1_1_sound.html", null ],
      [ "sf::SoundStream", "classsf_1_1_sound_stream.html", [
        [ "sf::Music", "classsf_1_1_music.html", null ],
        [ "sf::Music", "classsf_1_1_music.html", null ],
        [ "sf::Music", "classsf_1_1_music.html", null ],
        [ "sf::Music", "classsf_1_1_music.html", null ]
      ] ],
      [ "sf::SoundStream", "classsf_1_1_sound_stream.html", null ],
      [ "sf::SoundStream", "classsf_1_1_sound_stream.html", null ],
      [ "sf::SoundStream", "classsf_1_1_sound_stream.html", null ]
    ] ],
    [ "sf::String", "classsf_1_1_string.html", null ],
    [ "sf::Event::TextEvent", "structsf_1_1_event_1_1_text_event.html", null ],
    [ "priv::ThreadFunc", "structpriv_1_1_thread_func.html", [
      [ "priv::ThreadFunctor< T >", "structpriv_1_1_thread_functor.html", null ],
      [ "priv::ThreadFunctor< T >", "structpriv_1_1_thread_functor.html", null ],
      [ "priv::ThreadFunctor< T >", "structpriv_1_1_thread_functor.html", null ],
      [ "priv::ThreadFunctor< T >", "structpriv_1_1_thread_functor.html", null ],
      [ "priv::ThreadFunctorWithArg< F, A >", "structpriv_1_1_thread_functor_with_arg.html", null ],
      [ "priv::ThreadFunctorWithArg< F, A >", "structpriv_1_1_thread_functor_with_arg.html", null ],
      [ "priv::ThreadFunctorWithArg< F, A >", "structpriv_1_1_thread_functor_with_arg.html", null ],
      [ "priv::ThreadFunctorWithArg< F, A >", "structpriv_1_1_thread_functor_with_arg.html", null ],
      [ "priv::ThreadMemberFunc< C >", "structpriv_1_1_thread_member_func.html", null ],
      [ "priv::ThreadMemberFunc< C >", "structpriv_1_1_thread_member_func.html", null ],
      [ "priv::ThreadMemberFunc< C >", "structpriv_1_1_thread_member_func.html", null ],
      [ "priv::ThreadMemberFunc< C >", "structpriv_1_1_thread_member_func.html", null ]
    ] ],
    [ "sf::Time", "classsf_1_1_time.html", null ],
    [ "sf::Touch", "classsf_1_1_touch.html", null ],
    [ "sf::Event::TouchEvent", "structsf_1_1_event_1_1_touch_event.html", null ],
    [ "sf::Transform", "classsf_1_1_transform.html", null ],
    [ "sf::Transformable", "classsf_1_1_transformable.html", [
      [ "sf::Shape", "classsf_1_1_shape.html", null ],
      [ "sf::Shape", "classsf_1_1_shape.html", null ],
      [ "sf::Shape", "classsf_1_1_shape.html", null ],
      [ "sf::Shape", "classsf_1_1_shape.html", null ],
      [ "sf::Sprite", "classsf_1_1_sprite.html", null ],
      [ "sf::Sprite", "classsf_1_1_sprite.html", null ],
      [ "sf::Sprite", "classsf_1_1_sprite.html", null ],
      [ "sf::Sprite", "classsf_1_1_sprite.html", null ],
      [ "sf::Text", "classsf_1_1_text.html", null ],
      [ "sf::Text", "classsf_1_1_text.html", null ],
      [ "sf::Text", "classsf_1_1_text.html", null ],
      [ "sf::Text", "classsf_1_1_text.html", null ]
    ] ],
    [ "sf::Utf< N >", "classsf_1_1_utf.html", null ],
    [ "sf::Utf< 16 >", "classsf_1_1_utf_3_0116_01_4.html", null ],
    [ "sf::Utf< 32 >", "classsf_1_1_utf_3_0132_01_4.html", null ],
    [ "sf::Utf< 8 >", "classsf_1_1_utf_3_018_01_4.html", null ],
    [ "sf::Vector2< T >", "classsf_1_1_vector2.html", null ],
    [ "sf::Vector2< float >", "classsf_1_1_vector2.html", null ],
    [ "sf::Vector2< unsigned int >", "classsf_1_1_vector2.html", null ],
    [ "sf::Vector3< T >", "classsf_1_1_vector3.html", null ],
    [ "sf::Vertex", "classsf_1_1_vertex.html", null ],
    [ "sf::VideoMode", "classsf_1_1_video_mode.html", null ],
    [ "sf::View", "classsf_1_1_view.html", null ]
];